# Generated by Django 3.2.15 on 2022-09-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozluk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='image',
            field=models.ImageField(upload_to='terms'),
        ),
    ]
