# Generated by Django 3.2.9 on 2023-03-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozluk', '0009_alter_term_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='image',
            field=models.ImageField(blank=True, upload_to='terms'),
        ),
    ]
