# Generated by Django 3.2.9 on 2023-03-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozluk', '0010_alter_term_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='category',
            field=models.ManyToManyField(null=True, to='sozluk.Category'),
        ),
        migrations.AlterField(
            model_name='term',
            name='image',
            field=models.ImageField(null=True, upload_to='terms'),
        ),
    ]
